### ISSUE TITLE
vidrl_upload: fix `serum_strain` used for human sera measurements

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/fauna#166]
While working on #161, we learned that VIDRL uses proxies for human sera references that do not exactly match the vaccine strains listed in [VACCINE_MAPPING](https://github.com/nextstrain/fauna/blob/63af127eb591c594424a1229996de4336aa66544/tdb/vidrl_upload.py#L26-L55).

We should update the mapping to the correct proxy strains that are used in the flat files. Because the `serum_strain` is one of the [index fields](https://github.com/nextstrain/fauna/blob/63af127eb591c594424a1229996de4336aa66544/tdb/upload.py#L51), we will need to delete and re-upload the previously ingested human sera data to correct them. 

## TODOs

- [x] https://github.com/nextstrain/fauna/pull/167
- [x] delete [previously ingested human sera data](https://github.com/nextstrain/fauna/issues/158#issuecomment-2318611921) 
- [ ] re-upload with the updated `VACCINE_MAPPING`.

**Comment by joverlee521** [comment]
Deleted previously ingested human sera records with

```shell
$ envdir ../env.d/seasonal-flu/ python3 scripts/delete_records.py -db vidrl_tdb -v flu --filter serum_host:human
Connected to the "vidrl_tdb" database
Delete filters: {'serum_host': 'human'}
Delete intervals: {}
Deleted 7283 records
```

**Comment by joverlee521** [comment]
Used this [Snakefile](https://gist.github.com/joverlee521/f88da0703c5b51fdfd0d37f502e3e518) to re-upload all human sera data from 2024. This uploaded 7859 measurements (576 new measurements from https://github.com/fludata/VIDRL-Melbourne-WHO-CC/commit/7f71cbca8e6f3d964b2d036386513a148d04521a that were missed in my [previous backfill](https://github.com/nextstrain/fauna/issues/158#issuecomment-2318611921))
