### ISSUE TITLE
Fix H3 vaccine strains

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/fauna#174]
Details on [Slack](https://bedfordlab.slack.com/archives/C03KWDET9/p1734438852908179). 

## TODOs

General improvements:
- [x] Standardize capitalization of location in strain names (e.g. `DistrictofColumnbia` -> `DistrictOfColumbia`)
- [x] https://github.com/nextstrain/fauna/pull/176

Data clean up:
- [x] remove `A/Croatia/10136/RV/2023` sequences since they are duplicates of `A/Croatia/10136RV/2023`
- [x] remove `A/DistrictofColumbia/27/2023` sequences and reupload so they have `A/DistrictOfColumbia/27/2023` strain names
- [x] rename all test and reference virus names in titers for `A/Croatia/10136RV/2023` and `A/DistrictOfColumbia/27/2023`

Post clean up:
- [x] https://github.com/nextstrain/seasonal-flu/pull/203

**Comment by joverlee521** [comment]
> Standardize capitalization of location in strain names

This has proven to be more complicated than I initially thought... 

I wanted to use `geo_synonyms.tsv` to standardize locations in strain names, where I would do lower case string comparisons against the `label` column and then standardize on whatever capitalization was used in the `label` column. However, there are labels for **different** locations that would be duplicates in lower case string comparisons, e.g. [Hanam/South Korea](https://github.com/nextstrain/fauna/blob/72ade300d825536c04e8587a82dc6b0e19de0220/source-data/geo_synonyms.tsv#L2965) and [HaNam/Vietnam](https://github.com/nextstrain/fauna/blob/72ade300d825536c04e8587a82dc6b0e19de0220/source-data/geo_synonyms.tsv#L3848) would both match `hanam`. 

This duplicate location label is already an issue for [geolocation assignments](https://github.com/nextstrain/fauna/issues/135) so I thought I would tackle it here as well. I wanted to use the GISAID provided location metadata to make sure the label and the country matched. Then I realized the [virus strain name](https://github.com/nextstrain/fauna/blob/72ade300d825536c04e8587a82dc6b0e19de0220/vdb/flu_upload.py#L140) and the [sequence strain name](https://github.com/nextstrain/fauna/blob/72ade300d825536c04e8587a82dc6b0e19de0220/vdb/flu_upload.py#L161) are curated _separately_ and the sequence data do _not_ include the GISAID location metadata. I can create a map of the virus strain name to the GISAID EPI ISL that can be used to match the sequence strain name instead of curating them separately. However, this idea just does not work for the strain names in the titer data because they do not have location metadata. Titer data mostly do not include the GISAID EPI ISL so I cannot think of how to reliably match titer strain name to the sequence strain names...

Even if I can tackle all of the above, this will only standardize strain names for new uploads. If `geo_synonyms.tsv` is updated, it does not update virus records _already_ in fauna.  This is further complicated by the fact that we use `strain` as the index field for viruses and the `virus_strain` and `serum_strain` are used to create the index for titer records.

All that is to say this is taking longer than I would like for fixing this specific data issue, so I plan to do some short term fixes before tackling the larger issue of standardizing locations in strain names.

1. Add entries to `flu_fix_location_label.tsv` to change the location labels. The `flu_fix_location_label.tsv` is used in both the vdb and tdb uploads, so these fixes would apply across sequence and titer strain names: 
    - `DistrictofColumbia` -> `DistrictOfColumbia`
    - `A/Croatia/10136/RV/2023` -> `A/Croatia/10136RV/2023`

2. Remove the "bad" strains from the vdb/flu_* tables and re-upload them to fix their strain names.
3. Remove the titer records with "bad" strains from tdb/* tables and re-upload them to fix their strain names.

**Comment by joverlee521** [comment]
Manually cleaned up sequence and titer data in fauna and running [uploads to S3](https://github.com/nextstrain/seasonal-flu/actions/runs/12838781538) in seasonal-flu.

**Comment by joverlee521** [comment]
Closing since this specific data issue has been fixed in fauna. In the long term, the geolocation standardization issues will be easier to fix once we tackle #162.
